# Navigation
curriculum_title:
  default: Visit the Curriculum
  description: "This text will be displayed in the curriculum navigation item"
curriculum_title_short:
  default: Curriculum
  description: "This is the short version of curriculum title used for mobile devices"
curriculum_src:
  default: https://www.freecodecamp.org/learn
  description: "This the link to related language curriculum"

# Analytics
Google_Tag_Manager:
  default: ""
  description: "Google Tag Manager ID"

# Footer description section
footer_paragraph_1:
  default: "freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit
    organization (United States Federal Tax Identification Number:
    82-0779546)"
  description: "First footer paragraph"
footer_paragraph_2:
  default:
    "Our mission: to help people learn to code for free. We accomplish this
    by creating thousands of videos, articles, and interactive coding
    lessons - all freely available to the public. We also have thousands
    of freeCodeCamp study groups around the world."
  description: "Second footer paragraph"
footer_paragraph_3:
  default: "Donations to freeCodeCamp go toward our education initiatives, and
    help pay for servers, services, and staff."
  description: "Second footer paragraph"
footer_donation_cta:
  default: "You can make a tax-deductible donation here."
  description: "Footer donation paragraph"

# Footer columns section
footer_columns_header:
  default: "Trending Guides"
  description: "Header for footer link columns"
article0title: "10 to the Power of 0"
article0link: "https://www.freecodecamp.org/news/10-to-the-power-of-0-the-zero-exponent-rule-and-the-power-of-zero-explained/"
article1title: "Git Reset to Remote"
article1link: "https://www.freecodecamp.org/news/git-reset-to-remote-head-how-to-reset-a-remote-branch-to-origin/"
article2title: "R Value in Statistics"
article2link: "https://www.freecodecamp.org/news/what-is-a-correlation-coefficient-r-value-in-statistics-explains/"
article3title: "What is Economics?"
article3link: "https://www.freecodecamp.org/news/what-is-economics/"
article4title: "Module Exports"
article4link: "https://www.freecodecamp.org/news/node-module-exports-explained-with-javascript-export-function-examples/"
article5title: "Python VS JavaScript"
article5link: "https://www.freecodecamp.org/news/python-vs-javascript-what-are-the-key-differences-between-the-two-popular-programming-languages/"
article6title: "Model View Controller"
article6link: "https://www.freecodecamp.org/news/model-view-architecture/"
article7title: "React Testing Library"
article7link: "https://www.freecodecamp.org/news/react-testing-library-tutorial-javascript-example-code/"
article8title: "ASCII Table Chart"
article8link: "https://www.freecodecamp.org/news/ascii-table-hex-to-ascii-value-character-code-chart-2/"
article9title: "Data Validation"
article9link: "https://www.freecodecamp.org/news/form-validation-with-html5-and-javascript/"
article10title: "Recursion"
article10link: "https://www.freecodecamp.org/news/what-is-recursion-in-javascript/"
article11title: "ISO File"
article11link: "https://www.freecodecamp.org/news/what-is-an-iso-file-explained-in-plain-english/"
article12title: "ADB"
article12link: "https://www.freecodecamp.org/news/adb-android-install-guide-drivers-and-commands/"
article13title: "MBR VS GPT"
article13link: "https://www.freecodecamp.org/news/mbr-vs-gpt-whats-the-difference-between-an-mbr-partition-and-a-gpt-partition-solved/"
article14title: "Debounce"
article14link: "https://www.freecodecamp.org/news/javascript-debounce-example/"
article15title: "Helm Chart"
article15link: "https://www.freecodecamp.org/news/what-is-a-helm-chart-tutorial-for-kubernetes-beginners/"
article16title: "80-20 Rule"
article16link: "https://www.freecodecamp.org/news/the-80-20-rule-pareto-principle-explained-in-plain-english/"
article17title: "OSI Model"
article17link: "https://www.freecodecamp.org/news/osi-model-networking-layers-explained-in-plain-english/"
article18title: "HTML Link Code"
article18link: "https://www.freecodecamp.org/news/html-link-code-how-to-insert-a-link-to-a-website-with-href-3/"
article19title: "SDLC"
article19link: "https://www.freecodecamp.org/news/what-is-sdlc-software-development-life-cycle-phases-methodologies-and-processes-explained/"
article20title: "Inductive VS Deductive"
article20link: "https://www.freecodecamp.org/news/inductive-vs-deductive-reasoning/"
article21title: "JavaScript Empty Array"
article21link: "https://www.freecodecamp.org/news/check-if-javascript-array-is-empty-or-not-with-length/"
article22title: "Best Instagram Post Time"
article22link: "https://www.freecodecamp.org/news/the-best-time-to-post-on-instagram-the-best-days-and-times-to-reach-your-ig-followers/"
article23title: "Garbage Collection in Java"
article23link: "https://www.freecodecamp.org/news/garbage-collection-in-java-what-is-gc-and-how-it-works-in-the-jvm/"
article24title: "Auto-Numbering in Excel"
article24link: "https://www.freecodecamp.org/news/auto-numbering-in-excel/"
article25title: "JavaScript Keycode List"
article25link: "https://www.freecodecamp.org/news/javascript-keycode-list-keypress-event-key-codes/"
article26title: "JavaScript Reverse Array"
article26link: "https://www.freecodecamp.org/news/javascript-array-reverse-tutorial-with-example-js-code/"
article27title: "How to Screenshot on Mac"
article27link: "https://www.freecodecamp.org/news/how-to-take-a-screenshot-on-a-mac-keyboard-shortcut/"
article28title: "How to Reverse Image Search"
article28link: "https://www.freecodecamp.org/news/how-to-reverse-image-search-on-your-phone-or-desktop/"
article29title: "Ternary Operator JavaScript"
article29link: "https://www.freecodecamp.org/news/ternary-operator-javascript-if-statement-tutorial/"

footer_our_org_header:
  default: "Our Nonprofit"
  description: "Title for organizational links"
footer_about_link: "https://www.freecodecamp.org/news/about/"
footer_about_text: "About"
footer_Alumni_Network_link: "https://www.linkedin.com/school/free-code-camp/people/"
footer_Alumni_Network_text: "Alumni Network"
footer_Open_Source_link: "https://github.com/freeCodeCamp/"
footer_Open_Source_text: "Open Source"
footer_Shop_link: "https://www.freecodecamp.org/shop/"
footer_Shop_text: "Shop"
footer_Support_link: "https://www.freecodecamp.org/news/support/"
footer_Support_text: "Support"
footer_Sponsors_link: "https://www.freecodecamp.org/news/sponsors/"
footer_Sponsors_text: "Sponsors"
footer_Academic_Honesty_link: "https://www.freecodecamp.org/news/academic-honesty-policy/"
footer_Academic_Honesty_text: "Academic Honesty"
footer_Code_of_Conduct_link: "https://www.freecodecamp.org/news/code-of-conduct/"
footer_Code_of_Conduct_text: "Code of Conduct"
footer_Privacy_Policy_link: "https://www.freecodecamp.org/news/privacy-policy/"
footer_Privacy_Policy_text: "Privacy Policy"
footer_Terms_of_Service_link: "https://www.freecodecamp.org/news/terms-of-service/"
footer_Terms_of_Service_text: "Terms of Service"
footer_Copyright_Policy_link: "https://www.freecodecamp.org/news/copyright-policy/"
footer_Copyright_Policy_text: "Copyright Policy"
